apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cicdkubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-cicdkubernetes
  template:
    metadata:
      labels:
        app: demo-cicdkubernetes
    spec:
      containers:
      - name: demo-cicdkubernetes
        image: demo-cicdkubernetes:latest   # local image
        imagePullPolicy: IfNotPresent   # important for local builds
        ports:
        - containerPort: 8080

