apiVersion: v1
kind: Service
metadata:
  name: demo-CICDkubernetes-service
spec:
  type: NodePort
  selector:
    app: demo-CICDkubernetes
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
